name: Trivy Scan

on:
    workflow_dispatch: {}
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

permissions:
    contents: read

jobs:
    trivy-scan:
        runs-on: 'ubuntu-latest'
        permissions:
            security-events: write
            contents: read

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
              with:
                  egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Generate Trivy Vulnerability Report
              uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # master
              with:
                  scan-type: 'fs'
                  output: trivy-results.sarif
                  format: sarif
                  exit-code: 0

            - name: Upload Trivy Artifacts
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              if: always()
              with:
                  name: trivy-results.sarif
                  path: trivy-results.sarif

            - name: Upload Vulnerability Scan Results
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                  name: trivy-results
                  path: trivy-results.sarif
                  retention-days: 5

            - name: Check High/Critical Vulnerabilities
              id: checkVulnerabilities
              uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # master
              with:
                  scan-type: 'fs'
                  format: table
                  severity: HIGH,CRITICAL
                  ignore-unfixed: true
                  exit-code: 1
                  skip-setup-trivy: true
